---
title: "week-8-hw-eeb177"
author: "Krishna Krishnamurthy"
date: "March 4, 2017"
output: md_document
---

## Exercise 1: Exploring Data Frames

```{r}
# Adding rows and colums
# First we read in the data file we created for the class challenge

cats <- read.csv("/home/eeb177-student/Desktop/eeb177/class-assignments/data/feline-data.csv")
cats

# We want to add ages
age <- c(4,5,8)
cats <- cbind(cats,age)
cats

# Adding a new row
newRow <-list("tortoiseshell", 3.3, TRUE, 9)
cats <- rbind(cats, newRow)
# produces a NA value

levels(cats$coat) <- c(levels(cats$coat), "tortoiseshell")
# adding a new factor, otherwise R won't add the new row
cats <- rbind(cats, list("tortoiseshell", 3.3, TRUE, 9))
cats

# Removing rows
cats[-4,]
# we can also use the na.omit function
cats <- na.omit(cats)

# Appending data frame
cats <- rbind(cats, cats)
cats
# generates complicated row names

rownames(cats) <- NULL
cats
# simplifies the row names
```

```{r}
# Challenge 1
df <- data.frame(first = c('Krishna'), last = ("Krishnamurthy"), lucky_number = c(0), stringsAsFactors = FALSE)
df <- rbind(df, list("Irina", "Bird", 14))
df <- cbind(df, coffeetime = c(FALSE, TRUE))
df

# Challenge 2
source(file = "scripts/load-gapminder.R")

#script is:
download.file("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder-FiveYearData.csv", destfile = "data/gapminder-FiveYearData.csv")
gapminder <- read.csv(file = "data/gapminder-FiveYearData.csv")

# Challenge 3
str(gapminder)
# gapminder is a data frame with 6 columns, and 1704 observations. County and continent are factors; year is an integer value, pop, lifeExp and gdpPercap are all numeric vectors
```


## Exercise 2: Subsetting Data

```{r}
x <- c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) <- c('a', 'b', 'c', 'd', 'e')
x

# accessing indices
x[1]
x[4]

# multiple indices at once and multiple times
x[c(1,3)]
x[c(1,1,3,1)]

# slices
x[1:4]

x[6] # does not exist in this list; hence we get a NA
x[0] # never exists

# returning all values except one
x[-2]
x[-(1:3)] # exclude elements 1 through 3
x <- x[-4]
x
```

```{r}
# Challenge 1
x <- c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) <- c('a', 'b', 'c', 'd', 'e')
print(x)

x[2:4]
x[-c(1,5)]
x[c(2,3,4)]

# Challenge 2
x <- c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) <- c('a', 'b', 'c', 'd', 'e')
print(x)
x[-which(names(x) == "g")]
# A and C are correct;names(x) == "g" does not return any true values because there were none passed to the command. 

# Challenge 3
x <- c(5.4, 6.2, 7.1, 4.8, 7.5)
names(x) <- c('a', 'b', 'c', 'd', 'e')
print(x)
x_subset <- x[x<7 & x>4]
print(x_subset)

# Challenge 4
m <- matrix(1:18, nrow=3, ncol=6)
print(m)
m[2,c(4,5)] # this extracts 11 and 14

# Challenge 5
xlist <- list(a = "Software Carpentry", b = 1:10, data = head(iris))
# we can extract 2 from xlist with the following commands
xlist$b[2]
xlist[[2]][2]
xlist[["b"]][2]

# Challenge 6
mod <- aov(pop ~ lifeExp, data=gapminder)
attributes(mod)
mod$df.residual

# Challenge 7
# fixing errors
# gapminder[gapminder$year = 1957,]
gapminder[gapminder$year == 1957,]
# gapminder[,-1:4]
gapminder[,-c(1:4)]
# gapminder[gapminder$lifeExp > 80]
gapminder[gapminder$lifeExp > 80,]
# gapminder[1, 4, 5]
gapminder[1, c(4, 5)]
# gapminder[gapminder$year == 2002 | 2007,]
gapminder[gapminder$year == 2002 | gapminder$year == 2007,]
gapminder[gapminder$year %in% c(2002, 2007),]

# Challenge 8
# 1. gapminder is a dataframe and needs two columns. gapminder[1:20, ] is a subset with the first 20 rows and all columns
gapminder_small <- gapminder[c(1:9, 19:23),] # gives rows 1 through 9 and 19 through 23
```


## Exercise 3: Creating Publication Quality Graphics

